name: deprem_destek
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: 2.19.1
  flutter: 3.7.1

dependencies:
  cloud_firestore: 4.3.1
  collection: 1.17.0
  cupertino_icons: 1.0.2
  dio: 4.0.6
  firebase_auth: 4.2.5
  firebase_core: 2.4.1
  flutter:
    sdk: flutter
  flutter_bloc: 8.1.1
  font_awesome_flutter: 10.3.0
  freezed_annotation: 2.2.0
  geolocator: 9.0.2
  google_geocoding_api: 1.2.0
  http: 0.13.5
  json_annotation: 4.8.0
  reactive_forms: 14.1.0

dev_dependencies:
  build_runner: 2.3.3
  flutter_test:
    sdk: flutter
  freezed: 2.3.2
  json_serializable: 6.6.1
  very_good_analysis: 3.1.0

flutter:
  assets:
    - assets/images/
    - assets/images/location/

  uses-material-design: true

