name: PR Check

on:
  pull_request:
    branches: [master, develop]

jobs:
  test:
    name: Test Flutter (Web)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: "3.7.1"
      - run: flutter pub get
      - run: flutter pub run build_runner build --delete-conflicting-outputs
      - run: flutter analyze
      - run: dart format . --set-exit-if-changed
